name: kopamnos
favicon: null
layout_spectrum: 0.4141308655962348
typography_spectrum: 0.8791149195749313
title: KopamNos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7561890601646155
  lightness: 0.1929198051802814
  saturation: 0.6140788719058037
  rhythmicContrast: 0.7044718654360622
purpose: []
